name: friendly-neighbor
version: '0.1'
summary: Friendly Neighbor network service
description: |
  Server that responds to ARP (IPv4) and NDP (IPv6) requests on behalf of neighboring machines. Useful for keeping sleeping machines accessible on the network.

grade: devel
confinement: strict
base: core22

apps:
  friendly-neighbor:
    command: bin/friendly-neighbor-wrapper
    daemon: simple
    plugs:
      - network-bind
      - network-control
      - hardware-observe

parts:
  friendly-neighbor:
    plugin: dump
    source: .
    source-type: local
    build-packages:
      - libpcap-dev
    build-snaps:
      - zig/latest/edge
    override-build: |
      craftctl default
      zig build
    stage-packages:
      - libpcap0.8
    stage:
      - bin/friendly-neighbor
      - usr/lib/*
    organize:
      zig-out/bin/friendly_neighbor: bin/friendly-neighbor
  
  scripts:
    plugin: dump
    source: snap/local/bin
    organize:
      service-wrapper: bin/friendly-neighbor-wrapper
      manage-config: bin/manage-config