name: friendly-neighbor
version: '0.1'
summary: Friendly Neighbor network service
description: |
  Server that responds to ARP (IPv4) and NDP (IPv6) requests on behalf of neighboring machines. Useful for keeping sleeping machines accessible on the network.

grade: devel
confinement: strict
base: core22

apps:
  friendly-neighbor:
    command: bin/friendly-neighbor-wrapper
    daemon: simple
    plugs:
      - network-bind
      - network-control
      - hardware-observe

parts:
  friendly-neighbor:
    plugin: dump
    source: .
    source-type: local
    build-packages:
      - libpcap-dev
      - proxychains
    build-snaps:
      - zig/latest/edge
    override-build: |
      craftctl default

      # Extract the protocol, host, and port from the http_proxy variable
      host_and_port=${http_proxy#http://}
      host_and_port=${host_and_port%%/*}
      hostname=${host_and_port%:*}
      port=${host_and_port#*:}

      # Create a temporary proxychains configuration file
      proxychains_conf="$(mktemp)"
      cat > "$proxychains_conf" <<EOF
      strict_chain
      proxy_dns
      tcp_read_time_out 15000
      tcp_connect_time_out 8000
      [ProxyList]
      socks5 $hostname $port
      EOF

      PROXYCHAINS_CONF_FILE="$proxychains_conf" proxychains zig build

      # Clean up temporary file
      rm "$proxychains_conf"
    stage-packages:
      - libpcap0.8
    stage:
      - bin/friendly-neighbor
      - usr/lib/*
    organize:
      zig-out/bin/friendly_neighbor: bin/friendly-neighbor
  
  scripts:
    plugin: dump
    source: snap/local/bin
    organize:
      service-wrapper: bin/friendly-neighbor-wrapper
      manage-config: bin/manage-config