name: friendly-neighbor
summary: Friendly Neighbor network service
description: |
  Server that responds to ARP (IPv4) and NDP (IPv6) requests on behalf of neighboring machines. Useful for keeping sleeping machines accessible on the network.
license: MIT
source-code: https://github.com/danielpgross/friendly_neighbor
confinement: strict
base: core22
adopt-info: friendly-neighbor

architectures:
  - build-on: amd64
  - build-on: arm64

apps:
  friendly-neighbor:
    command: bin/friendly-neighbor-wrapper
    daemon: simple
    plugs:
      - network-bind
      - network-control
      - hardware-observe

parts:
  friendly-neighbor:
    plugin: dump
    source: .
    source-type: local
    build-packages:
      - libpcap-dev
      - curl
    build-snaps:
      - zig/latest/edge
    override-build: |
      craftctl default

      # Manually download the zig-clap package, since the Zig package manager doesn't yet support
      # using an HTTP proxy.
      ZIG_CACHE_PATH="$CRAFT_PART_BUILD/zig-cache/"
      EXTRACT_PATH="${ZIG_CACHE_PATH}p/1220f48518ce22882e102255ed3bcdb7aeeb4891f50b2cdd3bd74b5b2e24d3149ba2"
      TMP_FILE="/tmp/zig-clap.tar.gz"
      curl -L -o "$TMP_FILE" "https://github.com/Hejsil/zig-clap/archive/f49b94700e0761b7514abdca0e4f0e7f3f938a93.tar.gz"

      PRECOMPUTED_HASH=2737da5e8af7c1e17d2c4b7fa60fa9447720d8a47671bb087d1a7b0c7e7a420d
      COMPUTED_HASH=$(sha256sum $TMP_FILE | awk '{print $1}')

      if [[ "$COMPUTED_HASH" == "$PRECOMPUTED_HASH" ]]; then  
        mkdir -p "$EXTRACT_PATH"
        tar -xzf "$TMP_FILE" -C "$EXTRACT_PATH" --strip-components=1
      else
        echo "Hash mismatch while downloading zig-clap package dependency. File may be corrupted."
        exit 1
      fi

      # Populate metadata
      VERSION="$(zig build --global-cache-dir "$ZIG_CACHE_PATH" version)"
      # Also append the Zig version, since we're building from edge
      ZIG_VERSION="$(zig version)"
      craftctl set version="${VERSION}+zig-${ZIG_VERSION%%+*}"
      if [[ $VERSION == *"dev" ]]; then
        GRADE="devel"
      else
        GRADE="stable"
      fi
      craftctl set grade="$GRADE"

      zig build -Dcpu=baseline -Doptimize=ReleaseSafe --global-cache-dir "$ZIG_CACHE_PATH"
      mkdir -p $CRAFT_PART_INSTALL/bin
      cp zig-out/bin/friendly_neighbor $CRAFT_PART_INSTALL/bin/friendly-neighbor
    stage-packages:
      - libpcap0.8
    stage:
      - bin/friendly-neighbor
      - usr/lib/*
  
  scripts:
    plugin: dump
    source: snap/local/bin
    organize:
      service-wrapper: bin/friendly-neighbor-wrapper
      manage-config: bin/manage-config